name: Ejercicio 4

on:
  push:
    branches: [ main ]

jobs:
  test-multi-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout del c√≥digo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ejecutar tests
        run: npm test

      - name: mostrar sistema operativo
        run: echo "Sistema operativo:${{ runner.os }}"

      - name: solo en Linux
        if: runner.os == 'Linux'
        run: echo "este step solo aparece en Linux"
