name: ejercicio 1

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: step 1 - saludo
      run: echo "Hola, mi nombre es Oscar Javier"

    - name: step 2 - fecha actual
      run: date

    - name: step 3 - mostrar sistema operativo
      run: echo "sistema operativo del runner:$RUNNER_OS"