name: ejercicio 1

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: step 1 - saludo
      run: echo "Hola, mi nombre es Oscar Javier"

    - name: step 2 - fecha actual
      run: date

    - name: step 3 - mostrar sistema operativo
<<<<<<< HEAD
      run: echo "sistema operativo del runner:$RUNNER_OS"
=======
      run: echo "sistema operativo del runner:$RUNNER_OS"
>>>>>>> bbd5c8f351438635a3b8ce5d619bad86589be046
