name: jercicio 2

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout del repositorio
        uses: actions/checkout@v3

      - name: configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: instalar dependencias (si hubiera)
        run: npm install || true

      - name: ejecutar tests
        run: npm test